# Generated by Django 3.2 on 2022-01-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarplantreport',
            name='parameter',
            field=models.CharField(choices=[('generation', 'GENERATION'), ('irradiation', 'IRRADIATION')], max_length=100, verbose_name='parameter'),
        ),
    ]
